[package]
name = "efi-services"
version = "0.1.0"
authors = ["Xiaoyu Lu <xiaoyux.lu@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = { path = "../r-efi"}
efi-lib = { path = "../efi-lib" }
log = "0.4.8"
